# Generated by Django 5.0.6 on 2026-03-22 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('encrypted_file', models.FileField(blank=True, upload_to='encrypted/')),
                ('encrypted_aes_key', models.BinaryField(blank=True, null=True)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of original file', max_length=64)),
                ('received_hash', models.CharField(blank=True, help_text='SHA-256 hash computed after decryption', max_length=64)),
                ('digital_signature', models.BinaryField(blank=True, null=True)),
                ('signature_verified', models.BooleanField(default=False)),
                ('hash_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('encrypting', 'Encrypting'), ('sent', 'Sent'), ('received', 'Received'), ('decrypting', 'Decrypting'), ('verified', 'Verified'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('encryption_time_ms', models.FloatField(default=0)),
                ('hashing_time_ms', models.FloatField(default=0)),
                ('signing_time_ms', models.FloatField(default=0)),
                ('total_time_ms', models.FloatField(default=0)),
                ('cpu_usage_percent', models.FloatField(default=0)),
                ('memory_usage_mb', models.FloatField(default=0)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('auth_login', 'User Login'), ('auth_logout', 'User Logout'), ('auth_fail', 'Authentication Failed'), ('file_upload', 'File Uploaded'), ('file_encrypt', 'File Encrypted'), ('file_send', 'File Sent'), ('file_receive', 'File Received'), ('file_decrypt', 'File Decrypted'), ('hash_verify_pass', 'Hash Verification Passed'), ('hash_verify_fail', 'Hash Verification Failed'), ('sig_verify_pass', 'Signature Verification Passed'), ('sig_verify_fail', 'Signature Verification Failed'), ('key_generate', 'Key Generated'), ('key_rotate', 'Key Rotated'), ('key_revoke', 'Key Revoked'), ('transfer_complete', 'Transfer Complete'), ('transfer_reject', 'Transfer Rejected'), ('integrity_fail', 'Integrity Check Failed'), ('attack_detected', 'Potential Attack Detected')], max_length=30)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('verification_result', models.BooleanField(blank=True, null=True)),
                ('chain_hash', models.CharField(help_text='Hash chain: SHA256(prev_hash + current_data)', max_length=64)),
                ('previous_hash', models.CharField(blank=True, default='GENESIS', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_logs', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filetransfer')),
            ],
            options={
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(blank=True, help_text='RSA public key in PEM format')),
                ('key_fingerprint', models.CharField(blank=True, max_length=64)),
                ('key_version', models.PositiveIntegerField(default=0)),
                ('key_created_at', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_key_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
