# Generated by Django 5.0.6 on 2026-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='decrypted_file',
            field=models.FileField(blank=True, upload_to='decrypted/'),
        ),
    ]
